-- ============================================================
-- ESQUEMA POSTGRESQL PARA SUPABASE - AGENDA TECNO REVEST
-- Execute este script no SQL Editor do seu projeto Supabase
-- ============================================================

-- 1. Tabela de Usuários
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT 'Administrador',
  role TEXT NOT NULL DEFAULT 'Gestor de Obras',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Equipes
CREATE TABLE IF NOT EXISTS public.teams (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#2258A3',
  leader TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Colaboradores
CREATE TABLE IF NOT EXISTS public.employees (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  team_id TEXT REFERENCES public.teams(id) ON DELETE SET NULL,
  phone TEXT DEFAULT '',
  email TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Projetos / Obras
CREATE TABLE IF NOT EXISTS public.projects (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  client TEXT NOT NULL,
  team_id TEXT REFERENCES public.teams(id) ON DELETE SET NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  period TEXT NOT NULL DEFAULT 'full_day',
  start_time TEXT NOT NULL DEFAULT '08:00',
  end_time TEXT NOT NULL DEFAULT '18:00',
  status TEXT NOT NULL DEFAULT 'progress',
  location TEXT DEFAULT '',
  description TEXT DEFAULT '',
  stages JSONB DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- HABILITAR SEGURANÇA POR LINHA (RLS) E PERMISSÕES PÚBLICAS (ANON)
-- ============================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso livre para a chave 'anon' do Supabase
CREATE POLICY "Acesso total publico a users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total publico a teams" ON public.teams FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total publico a employees" ON public.employees FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total publico a projects" ON public.projects FOR ALL USING (true) WITH CHECK (true);

-- Habilitar Public Read/Write via API
GRANT ALL ON TABLE public.users TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.teams TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.employees TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.projects TO anon, authenticated, service_role;

-- ============================================================
-- DADOS INICIAIS (MOCK SEED DATA)
-- ============================================================

INSERT INTO public.users (username, password, name, role) VALUES
('Admin', 'Admin', 'Administrador', 'Gestor de Obras')
ON CONFLICT (username) DO NOTHING;

INSERT INTO public.teams (id, name, color, leader) VALUES
('team_1', 'Equipe Azul', '#2258A3', 'Felipe'),
('team_2', 'Equipe Laranja', '#F38221', 'Marcos Souza'),
('team_3', 'Equipe Verde', '#38a169', 'Fernando Lima')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.employees (id, name, role, team_id, phone, email, status) VALUES
('emp_1', 'Carlos Silva', 'Aplicador Epóxi', 'team_1', '(11) 98765-4321', 'carlos@tecnorevest.com.br', 'active'),
('emp_2', 'Roberto Santos', 'Preparador de Piso', 'team_1', '(11) 97654-3210', 'roberto@tecnorevest.com.br', 'active'),
('emp_3', 'Lucas Mendes', 'Técnico Poliuretano', 'team_2', '(11) 96543-2109', 'lucas@tecnorevest.com.br', 'active'),
('emp_4', 'André Oliveira', 'Auxiliar de Aplicação', 'team_3', '(11) 95432-1098', 'andre@tecnorevest.com.br', 'active')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.projects (id, name, client, team_id, start_date, end_date, period, start_time, end_time, status, location, description) VALUES
('proj_1', 'Revestimento Epóxi - Galpão 01', 'Logística Brasil Ltda', 'team_1', '2026-07-06', '2026-07-10', 'full_day', '08:00', '18:00', 'progress', 'Av. Industrial, 1000 - Barueri/SP', 'Aplicação de autonivelante epóxi 2mm'),
('proj_2', 'Piso PU Antiderrapante', 'Cervejaria Artesanal', 'team_2', '2026-07-08', '2026-07-14', 'custom', '13:30', '19:00', 'planned', 'Rua das Flores, 500 - Jundiaí/SP', 'Piso uretano 4mm para área molhada'),
('proj_3', 'Nivelamento Cimentício - Estacionamento', 'Shopping Plaza', 'team_3', '2026-07-13', '2026-07-20', 'full_day', '08:00', '18:00', 'progress', 'Al. Rio Negro, 200 - Alphaville/SP', 'Recuperação de substrato cimentício'),
('proj_4', 'Laboratório MedLab', 'Farmacêutica SP', 'team_1', '2026-07-20', '2026-07-22', 'custom', '08:00', '12:00', 'planned', 'Rua Vergueiro, 1200 - São Paulo/SP', 'Piso condutivo para sala limpa')
ON CONFLICT (id) DO NOTHING;
